### ISSUE TITLE
Docker Install Error on Mac

### ISSUE THREAD

**Issue by s-naveen** [google/fully-homomorphic-encryption#10] opened 2021-06-22 07:55 UTC
Using Mac catalina

`2021/06/22 07:39:43 Downloading https://releases.bazel.build/4.0.0/release/bazel-4.0.0-linux-x86_64...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Analyzing: 362 targets (17 packages loaded, 0 targets configured)
Analyzing: 362 targets (64 packages loaded, 909 targets configured)
Analyzing: 362 targets (82 packages loaded, 9004 targets configured)
Analyzing: 362 targets (105 packages loaded, 11569 targets configured)
INFO: Analyzed 362 targets (110 packages loaded, 18310 targets configured).
INFO: Found 362 targets...
[0 / 64] [Prepa] Writing script external/tfhe/libtfhe_foreign_cc/build_script.sh
INFO: From Compiling clang/utils/TableGen/RISCVVEmitter.cpp [for host]:
external/llvm-project/clang/utils/TableGen/RISCVVEmitter.cpp: In member function 'void {anonymous}::RVVType::applyModifier(llvm::StringRef)':
external/llvm-project/clang/utils/TableGen/RISCVVEmitter.cpp:644:27: warning: 'Log2EEW' may be used uninitialized in this function [-Wmaybe-uninitialized]
  644 |       ElementBitwidth = 1 << Log2EEW;
      |                         ~~^~~~~~~~~~
INFO: From Compiling clang/utils/TableGen/NeonEmitter.cpp [for host]:
external/llvm-project/clang/utils/TableGen/NeonEmitter.cpp: In static member function 'static {anonymous}::Type {anonymous}::Type::fromTypedefName(llvm::StringRef)':
external/llvm-project/clang/utils/TableGen/NeonEmitter.cpp:770:36: warning: 'NumLanes' may be used uninitialized in this function [-Wmaybe-uninitialized]
  770 |     T.Bitwidth = T.ElementBitwidth * NumLanes;
      |                  ~~~~~~~~~~~~~~~~~~^~~~~~~~~~
[46 / 467] BootstrapGNUMake external/rules_foreign_cc/toolchains/make [for host]; 29s processwrapper-sandbox ... (4 actions, 3 running)
[90 / 467] CcCmakeMakeRule external/tfhe/libtfhe/include; 23s processwrapper-sandbox ... (4 actions, 3 running)
[146 / 467] Compiling llvm/lib/Support/Signals.cpp [for host]; 1s processwrapper-sandbox ... (4 actions, 3 running)
INFO: From Compiling llvm/lib/Support/YAMLParser.cpp [for host]:
external/llvm-project/llvm/lib/Support/YAMLParser.cpp: In member function 'bool llvm::yaml::Scanner::findBlockScalarIndent(unsigned int&, unsigned int, unsigned int&, bool&)':
external/llvm-project/llvm/lib/Support/YAMLParser.cpp:268:5: warning: 'LongestAllSpaceLine' may be used uninitialized in this function [-Wmaybe-uninitialized]
  268 |     if (Position >= End)
      |     ^~
external/llvm-project/llvm/lib/Support/YAMLParser.cpp:1584:23: note: 'LongestAllSpaceLine' was declared here
 1584 |   StringRef::iterator LongestAllSpaceLine;
      |                       ^~~~~~~~~~~~~~~~~~~
INFO: From Compiling llvm/lib/Support/VirtualFileSystem.cpp [for host]:
external/llvm-project/llvm/lib/Support/VirtualFileSystem.cpp: In member function 'std::unique_ptr<llvm::vfs::RedirectingFileSystem::Entry> llvm::vfs::RedirectingFileSystemParser::parseEntry(llvm::yaml::Node*, llvm::vfs::RedirectingFileSystem*, bool)':
external/llvm-project/llvm/lib/Support/VirtualFileSystem.cpp:1616:5: warning: 'Kind' may be used uninitialized in this function [-Wmaybe-uninitialized]
 1616 |     switch (Kind) {
      |     ^~~~~~
INFO: From Compiling llvm/lib/Support/APFloat.cpp [for host]:
external/llvm-project/llvm/lib/Support/APFloat.cpp: In member function 'llvm::Expected<llvm::APFloatBase::opStatus> llvm::detail::IEEEFloat::convertFromDecimalString(llvm::StringRef, llvm::APFloatBase::roundingMode)':
external/llvm-project/llvm/lib/Support/APFloat.cpp:2794:16: warning: 'D.llvm::decimalInfo::lastSigDigit' may be used uninitialized in this function [-Wmaybe-uninitialized]
 2794 |     } while (p <= D.lastSigDigit);
      |              ~~^~~~~~~~~~~~~~~~~
external/llvm-project/llvm/lib/Support/APFloat.cpp:2753:58: warning: 'D.llvm::decimalInfo::firstSigDigit' may be used uninitialized in this function [-Wmaybe-uninitialized]
 2753 |     partCount = static_cast<unsigned int>(D.lastSigDigit - D.firstSigDigit) + 1;
      |                                           ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
[241 / 696] [Sched] Linking external/llvm-project/clang/clang-tblgen [for host] ... (4 actions, 2 running)
INFO: From Compiling llvm/lib/BinaryFormat/MsgPackDocument.cpp [for host]:
external/llvm-project/llvm/lib/BinaryFormat/MsgPackDocument.cpp: In member function 'bool llvm::msgpack::Document::readFromBlob(llvm::StringRef, bool, llvm::function_ref<int(llvm::msgpack::DocNode*, llvm::msgpack::DocNode, llvm::msgpack::DocNode)>)':
external/llvm-project/llvm/lib/BinaryFormat/MsgPackDocument.cpp:174:12: warning: 'N.llvm::msgpack::DocNode::<anonymous>.llvm::msgpack::DocNode::<unnamed union>::Raw.llvm::StringRef::Length' may be used uninitialized in this function [-Wmaybe-uninitialized]
  174 |       Node = getArrayNode();
      |       ~~~~~^~~~~~~~~~~~~~~~
[308 / 706] [Sched] Linking external/llvm-project/clang/clang-tblgen [for host]; 55s ... (4 actions, 2 running)
INFO: From Compiling llvm/lib/MC/WasmObjectWriter.cpp [for host]:
external/llvm-project/llvm/lib/MC/WasmObjectWriter.cpp: In member function 'uint64_t {anonymous}::WasmObjectWriter::writeOneObject(llvm::MCAssembler&, const llvm::MCAsmLayout&, {anonymous}::WasmObjectWriter::DwoMode)':
external/llvm-project/llvm/lib/MC/WasmObjectWriter.cpp:1885:22: warning: 'DataSectionIndex' may be used uninitialized in this function [-Wmaybe-uninitialized]
 1885 |     writeRelocSection(DataSectionIndex, "DATA", DataRelocations);
      |     ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
external/llvm-project/llvm/lib/MC/WasmObjectWriter.cpp:1884:22: warning: 'CodeSectionIndex' may be used uninitialized in this function [-Wmaybe-uninitialized]
 1884 |     writeRelocSection(CodeSectionIndex, "CODE", CodeRelocations);
      |     ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[363 / 706] [Sched] Linking external/llvm-project/clang/clang-tblgen [for host]; 116s ... (4 actions, 2 running)
INFO: From Compiling llvm/lib/MC/MachObjectWriter.cpp [for host]:
external/llvm-project/llvm/lib/MC/MachObjectWriter.cpp: In member function 'void llvm::MachObjectWriter::writeNlist(llvm::MachObjectWriter::MachSymbolData&, const llvm::MCAsmLayout&)':
external/llvm-project/llvm/lib/MC/MachObjectWriter.cpp:381:13: warning: 'AliaseeInfo' may be used uninitialized in this function [-Wmaybe-uninitialized]
  381 |     Address = AliaseeInfo->StringIndex;
      |     ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
[419 / 706] [Sched] Linking external/llvm-project/clang/clang-tblgen [for host]; 186s ... (4 actions, 3 running)
ERROR: /root/.cache/bazel/_bazel_root/595596dc4dacd40e54f4e8ca596c8a84/external/llvm-project/llvm/BUILD:1689:12: Generating code from table: lib/Target/RISCV/RISCV.td @llvm-project//llvm:RISCVCommonTableGen__gen_instr_info_genrule failed: (Killed): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
ERROR: /usr/src/fhe/transpiler/examples/calculator/BUILD:69:15 Action transpiler/examples/calculator/calculator_bool.bool.ir failed: (Killed): bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
INFO: Elapsed time: 599.389s, Critical Path: 210.46s
INFO: 1057 processes: 528 internal, 529 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully`

**Comment by dibakch** [comment] 2021-06-22 08:55
Thanks for reporting!  What was the command that you were running?

**Comment by s-naveen** [comment] 2021-06-22 10:16
> Thanks for reporting! What was the command that you were running?

docker build -t google-fhe-transpiler .

I just followed the steps mentioned in the readme.

**Comment by dibakch** [comment] 2021-06-22 17:34
Just out of curiosity: What is the max memory that you assign to docker?  You can find this in `Preferences` -> `Resources` -> `Advanced` as far as I can tell from this screenshot:
![screenshot](https://docs.docker.com/docker-for-mac/images/menu/prefs-advanced.png)

[The default for Docker on Mac seems to be 2 GB](https://docs.docker.com/docker-for-mac/), which on my Linux workstation is not enough to build LLVM (is was adding `--memory=2g` and LLVM failed to compile).  Could you set this to all memory that is available and try again?

Thanks :)

**Comment by jlogelin** [comment] 2021-06-23 02:41
I can confirm there is an error with the docker installation on a mac, even after I up my memory from 2g to 6g.

```
% docker build -t google-fhe-transpiler .
[+] Building 19.1s (13/13) FINISHED                                                                                                                                                              
 => [internal] load build definition from Dockerfile                                                                                                                                        0.0s
 => => transferring dockerfile: 37B                                                                                                                                                         0.0s
 => [internal] load .dockerignore                                                                                                                                                           0.0s
 => => transferring context: 2B                                                                                                                                                             0.0s
 => [internal] load metadata for docker.io/library/debian:bullseye                                                                                                                          1.0s
 => [auth] library/debian:pull token for registry-1.docker.io                                                                                                                               0.0s
 => [1/8] FROM docker.io/library/debian:bullseye@sha256:f5d8b0737991a13284b86adb3e6605f41794fcdfd5d0f0b36939f7e30b323358                                                                    0.0s
 => [internal] load build context                                                                                                                                                           0.0s
 => => transferring context: 12.63kB                                                                                                                                                        0.0s
 => CACHED [2/8] RUN apt-get update && apt-get install -y  gcc  git  libtinfo5  python  python3  python3-pip  wget                                                                          0.0s
 => CACHED [3/8] RUN wget -O bazelisk "https://github.com/bazelbuild/bazelisk/releases/download/v1.8.0/bazelisk-linux-amd64"  && test "cde5b2769d0633bb4fdc3e41800a1b2c867b68bd724b1dd2325  0.0s
 => CACHED [4/8] WORKDIR /usr/src/fhe/                                                                                                                                                      0.0s
 => CACHED [5/8] COPY .bazelversion .                                                                                                                                                       0.0s
 => CACHED [6/8] RUN bazelisk version                                                                                                                                                       0.0s
 => CACHED [7/8] COPY . .                                                                                                                                                                   0.0s
 => ERROR [8/8] RUN bazelisk build ...                                                                                                                                                     18.0s
------                                                                                                                                                                                           
 > [8/8] RUN bazelisk build ...:                                                                                                                                                                 
#13 0.320 2021/06/23 02:37:42 Downloading https://releases.bazel.build/4.0.0/release/bazel-4.0.0-linux-x86_64...                                                                                 
#13 10.49 Extracting Bazel installation...                                                                                                                                                       
#13 11.92 Starting local Bazel server and connecting to it...                                                                                                                                    
#13 13.87 Loading:                                                                                                                                                                               
#13 13.88 Loading: 0 packages loaded
#13 14.88 Loading: 0 packages loaded
#13 15.89 Loading: 0 packages loaded
#13 17.06 Loading: 0 packages loaded
#13 17.79 INFO: Repository llvm_toolchain instantiated at:
#13 17.79   /usr/src/fhe/WORKSPACE:59:15: in <toplevel>
#13 17.79 Repository rule llvm_toolchain defined at:
#13 17.79   /root/.cache/bazel/_bazel_root/595596dc4dacd40e54f4e8ca596c8a84/external/com_grail_bazel_toolchain/toolchain/rules.bzl:24:33: in <toplevel>
#13 17.79 ERROR: An error occurred during the fetch of repository 'llvm_toolchain':
#13 17.79    Traceback (most recent call last):
#13 17.79 	File "/root/.cache/bazel/_bazel_root/595596dc4dacd40e54f4e8ca596c8a84/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 110, column 37, in llvm_toolchain_impl
#13 17.79 		_download_llvm_preconfigured(rctx)
#13 17.79 	File "/root/.cache/bazel/_bazel_root/595596dc4dacd40e54f4e8ca596c8a84/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 169, column 17, in download_llvm_preconfigured
#13 17.79 		fail("Failed to detect host OS version: \n%s\n%s" % (exec_result.stdout, exec_result.stderr))
#13 17.79 Error in fail: Failed to detect host OS version: 
#13 17.79 
#13 17.79 Unsupported linux distribution and version: debian, 11
#13 17.80 ERROR: Error fetching repository: Traceback (most recent call last):
#13 17.80 	File "/root/.cache/bazel/_bazel_root/595596dc4dacd40e54f4e8ca596c8a84/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 110, column 37, in llvm_toolchain_impl
#13 17.80 		_download_llvm_preconfigured(rctx)
#13 17.80 	File "/root/.cache/bazel/_bazel_root/595596dc4dacd40e54f4e8ca596c8a84/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 169, column 17, in download_llvm_preconfigured
#13 17.80 		fail("Failed to detect host OS version: \n%s\n%s" % (exec_result.stdout, exec_result.stderr))
#13 17.80 Error in fail: Failed to detect host OS version: 
#13 17.80 
#13 17.80 Unsupported linux distribution and version: debian, 11
#13 17.82 ERROR: no such package '@llvm_toolchain//': Failed to detect host OS version: 
#13 17.82 
#13 17.82 Unsupported linux distribution and version: debian, 11
#13 17.83 INFO: Elapsed time: 7.285s
#13 17.83 INFO: 0 processes.
#13 17.83 FAILED: Build did NOT complete successfully (0 packages loaded)
#13 17.84 FAILED: Build did NOT complete successfully (0 packages loaded)
------
executor failed running [/bin/sh -c bazelisk build ...]: exit code: 1
```

**Comment by wobushizhanghua** [comment] 2021-06-23 03:10
> I can confirm there is an error with the docker installation on a mac, even after I up my memory from 2g to 6g.
> 
> ```
> % docker build -t google-fhe-transpiler .
> [+] Building 19.1s (13/13) FINISHED                                                                                                                                                              
>  => [internal] load build definition from Dockerfile                                                                                                                                        0.0s
>  => => transferring dockerfile: 37B                                                                                                                                                         0.0s
>  => [internal] load .dockerignore                                                                                                                                                           0.0s
>  => => transferring context: 2B                                                                                                                                                             0.0s
>  => [internal] load metadata for docker.io/library/debian:bullseye                                                                                                                          1.0s
>  => [auth] library/debian:pull token for registry-1.docker.io                                                                                                                               0.0s
>  => [1/8] FROM docker.io/library/debian:bullseye@sha256:f5d8b0737991a13284b86adb3e6605f41794fcdfd5d0f0b36939f7e30b323358                                                                    0.0s
>  => [internal] load build context                                                                                                                                                           0.0s
>  => => transferring context: 12.63kB                                                                                                                                                        0.0s
>  => CACHED [2/8] RUN apt-get update && apt-get install -y  gcc  git  libtinfo5  python  python3  python3-pip  wget                                                                          0.0s
>  => CACHED [3/8] RUN wget -O bazelisk "https://github.com/bazelbuild/bazelisk/releases/download/v1.8.0/bazelisk-linux-amd64"  && test "cde5b2769d0633bb4fdc3e41800a1b2c867b68bd724b1dd2325  0.0s
>  => CACHED [4/8] WORKDIR /usr/src/fhe/                                                                                                                                                      0.0s
>  => CACHED [5/8] COPY .bazelversion .                                                                                                                                                       0.0s
>  => CACHED [6/8] RUN bazelisk version                                                                                                                                                       0.0s
>  => CACHED [7/8] COPY . .                                                                                                                                                                   0.0s
>  => ERROR [8/8] RUN bazelisk build ...                                                                                                                                                     18.0s
> ------                                                                                                                                                                                           
>  > [8/8] RUN bazelisk build ...:                                                                                                                                                                 
> #13 0.320 2021/06/23 02:37:42 Downloading https://releases.bazel.build/4.0.0/release/bazel-4.0.0-linux-x86_64...                                                                                 
> #13 10.49 Extracting Bazel installation...                                                                                                                                                       
> #13 11.92 Starting local Bazel server and connecting to it...                                                                                                                                    
> #13 13.87 Loading:                                                                                                                                                                               
> #13 13.88 Loading: 0 packages loaded
> #13 14.88 Loading: 0 packages loaded
> #13 15.89 Loading: 0 packages loaded
> #13 17.06 Loading: 0 packages loaded
> #13 17.79 INFO: Repository llvm_toolchain instantiated at:
> #13 17.79   /usr/src/fhe/WORKSPACE:59:15: in <toplevel>
> #13 17.79 Repository rule llvm_toolchain defined at:
> #13 17.79   /root/.cache/bazel/_bazel_root/595596dc4dacd40e54f4e8ca596c8a84/external/com_grail_bazel_toolchain/toolchain/rules.bzl:24:33: in <toplevel>
> #13 17.79 ERROR: An error occurred during the fetch of repository 'llvm_toolchain':
> #13 17.79    Traceback (most recent call last):
> #13 17.79 	File "/root/.cache/bazel/_bazel_root/595596dc4dacd40e54f4e8ca596c8a84/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 110, column 37, in llvm_toolchain_impl
> #13 17.79 		_download_llvm_preconfigured(rctx)
> #13 17.79 	File "/root/.cache/bazel/_bazel_root/595596dc4dacd40e54f4e8ca596c8a84/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 169, column 17, in download_llvm_preconfigured
> #13 17.79 		fail("Failed to detect host OS version: \n%s\n%s" % (exec_result.stdout, exec_result.stderr))
> #13 17.79 Error in fail: Failed to detect host OS version: 
> #13 17.79 
> #13 17.79 Unsupported linux distribution and version: debian, 11
> #13 17.80 ERROR: Error fetching repository: Traceback (most recent call last):
> #13 17.80 	File "/root/.cache/bazel/_bazel_root/595596dc4dacd40e54f4e8ca596c8a84/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 110, column 37, in llvm_toolchain_impl
> #13 17.80 		_download_llvm_preconfigured(rctx)
> #13 17.80 	File "/root/.cache/bazel/_bazel_root/595596dc4dacd40e54f4e8ca596c8a84/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 169, column 17, in download_llvm_preconfigured
> #13 17.80 		fail("Failed to detect host OS version: \n%s\n%s" % (exec_result.stdout, exec_result.stderr))
> #13 17.80 Error in fail: Failed to detect host OS version: 
> #13 17.80 
> #13 17.80 Unsupported linux distribution and version: debian, 11
> #13 17.82 ERROR: no such package '@llvm_toolchain//': Failed to detect host OS version: 
> #13 17.82 
> #13 17.82 Unsupported linux distribution and version: debian, 11
> #13 17.83 INFO: Elapsed time: 7.285s
> #13 17.83 INFO: 0 processes.
> #13 17.83 FAILED: Build did NOT complete successfully (0 packages loaded)
> #13 17.84 FAILED: Build did NOT complete successfully (0 packages loaded)
> ------
> executor failed running [/bin/sh -c bazelisk build ...]: exit code: 1
> ```

I think it's not only an error on Mac OS but an error in the docker file.
get the same problem in Linux:
```
Step 8/8 : RUN bazelisk build ...
 ---> Running in 265ebd50c188
2021/06/23 03:03:42 Downloading https://releases.bazel.build/4.0.0/release/bazel-4.0.0-linux-x86_64...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
INFO: Repository llvm_toolchain instantiated at:
  /usr/src/fhe/WORKSPACE:59:15: in <toplevel>
Repository rule llvm_toolchain defined at:
  /root/.cache/bazel/_bazel_root/595596dc4dacd40e54f4e8ca596c8a84/external/com_grail_bazel_toolchain/toolchain/rules.bzl:24:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'llvm_toolchain':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/595596dc4dacd40e54f4e8ca596c8a84/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 110, column 37, in llvm_toolchain_impl
                _download_llvm_preconfigured(rctx)
        File "/root/.cache/bazel/_bazel_root/595596dc4dacd40e54f4e8ca596c8a84/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 169, column 17, in download_llvm_preconfigured
                fail("Failed to detect host OS version: \n%s\n%s" % (exec_result.stdout, exec_result.stderr))
Error in fail: Failed to detect host OS version: 

Unsupported linux distribution and version: debian, 11
ERROR: Error fetching repository: Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/595596dc4dacd40e54f4e8ca596c8a84/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 110, column 37, in llvm_toolchain_impl
```

**Comment by Cam2337** [comment] 2021-06-23 04:52
@jlogelin, @wobushizhanghua I believe that this is a separate issue from the previous errors seen here for macOS. It looks like the Docker image was broken by an upstream change to the `debian:bullseye` tag from a few hours ago.

Could you try and change:
```
FROM debian:bullseye
```

to:
```
FROM debian:bullseye-20210511
```

in the `Dockerfile` and trying again? This should pin to the previously-working parent image.

**Comment by s-naveen** [comment] 2021-06-23 10:02
@dibakch 
Yes thank you that fixed the problem.

**Comment by dibakch** [comment] 2021-06-23 12:15
Thanks for confirming!  In our tests, it worked fine with 8 GB memory and 1 GB swap.

We are preparing an update for the documentation.

**Closed** 2021-06-24 22:19 UTC
Labels: bug, documentation

**Comment by Savagist** [comment] 2022-01-15 10:25
Guys, I have a bug in the current version
PS. OS Windows
![error](https://user-images.githubusercontent.com/70751457/149618316-ef10338f-b463-4905-af05-7186112302fb.png)
However, when I change the version to debian:bullseye-20210511 в Dockerfile it's work
![work](https://user-images.githubusercontent.com/70751457/149618456-be03e087-b418-492e-b55c-90f456b1f382.png)
